### ISSUE TITLE
Metrics v2 Checklist

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/ocf-ml-metrics#3]
Metrics and features for v2

- [ ] Last day persistence
- [ ] Sigma thresholds
- [ ] PVLive comparison baseline intraday
- [ ] Read and write out CSV results directly
- [ ] Plotting of metrics

**Comment by jacobbieker** [comment]
@dantravers and @peterdudfield Merged the v1 stuff, so moved over some more ideas to this one for the next version of metrics

**Comment by dantravers** [comment]
Thanks @jacobbieker  - I've added this issue as another metric, as discussed the other day.  It's a financial metric - hopefully all you need is in the description. https://github.com/openclimatefix/ocf-ml-metrics/issues/4
